using System;

namespace CSharpKnowledge
{

	class Car { 
		// definitioN:
		//    backing field is the hidden field in the class that support properties, and
		//    backing field is invisible to class user. 
		// Automatic properties! 
		//No need to define backing fields. 
		public string PetName { get; set; }
		public int Speed { get; set; }

		// The name of the autogenerated private backing field is 
		// not visible within your C# code base. The only way to 
		// see it is to make use of a tool such as ildasm.exe.

		// update constructor to give default value;
	}


	// example 2:
	class Garage { 
		// The hidden backing field is set to 1. 
		public int NumberOfCars { get; set; } = 1;
		// The hidden backing field is set to a new Car object. 
		public Car MyAuto { get; set; } = new Car(); 
		public Garage(){} 
		public Garage( Car car, int number) { 
			MyAuto = car; NumberOfCars = number; 
		} 
	}



}




